- name: Configuring Django
  gather_facts: true
  become: true
  serial: 5
  hosts: backend
  remote_user: azroot

  tasks:
    - name: Delete Docker Containers
      shell: |
        sudo docker compose -f /home/temp/repo/configuration/docker/django/docker-compose.yml down

    - name: Wait for a few seconds
      pause:
        seconds: 30

    - name: Delete Images
      shell: |
        sudo docker image prune --all --force

    - name: Wait for a few seconds
      pause:
        seconds: 10

    - name: Start Docker Containers
      shell: |
        sudo docker compose -f /home/temp/repo/configuration/docker/django/docker-compose.yml up -d

    - name: Wait for a few seconds
      pause:
        seconds: 10

    - name: Restart Django
      shell: |
        sudo docker exec -d django_server python manage.py runserver 0.0.0.0:8000 --noreload
