- name: Configuring Django
  gather_facts: true
  become: true
  serial: 5
  hosts: backend
  remote_user: azroot

  tasks:
    - name: Create a New Directory
      file:
        path: /mnt/django
        state: directory
        mode: "0755"

    - name: Copy Configuration
      copy:
        remote_src: yes
        directory_mode: yes
        src: /home/temp/repo/configuration/django/
        dest: /mnt/django

    - name: Start Docker Containers
      shell: sudo docker compose -f /home/temp/repo/configuration/docker/django/docker-compose.yml up -d

    - name: Applying configurations
      shell: sudo docker exec -d django_server python manage.py runserver 0.0.0.0:8000 --noreload
