- name: Configuring Nginx
  gather_facts: true
  become: true
  serial: 5
  hosts: frontend
  remote_user: azroot

  tasks:
    - name: Create a New Directory
      file:
        path: /mnt/nginx
        state: directory
        mode: "0755"

    - name: Copy Configuration
      copy:
        remote_src: yes
        directory_mode: yes
        src: /home/temp/repo/configuration/nginx/
        dest: /mnt/nginx

    - name: Start Docker Containers
      shell: sudo docker compose -f /home/temp/repo/configuration/docker/nginx/docker-compose.yml up -d
