version: "3.5"
services:
  fronend:
    image: nginx:stable
    container_name: nginx_server
    volumes:
      - "/mnt/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "/mnt/nginx/static:/etc/nginx/static:ro"      
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - vnet1

networks:
  vnet1:
    driver: bridge
