name: Docker Hub_Push Django Image 
on: 
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Azure_Deploy Infrastructure"
    types:
      - completed
env: 
    DOCKER_PATH: '${{github.workspace}}/configuration/django'
    DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}    
    

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{env.DOCKER_PATH}}
          push: true
          tags: ${{env.DOCKER_USERNAME}}/django_app:latest